// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3HzK3qq23AYJoSQIurD2n6ExmLthRmqs',
    appId: '1:1044697442933:web:b4ab9aff8b9f4ebe45663c',
    messagingSenderId: '1044697442933',
    projectId: 'cmstask',
    authDomain: 'cmstask.firebaseapp.com',
    databaseURL: 'https://cmstask-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cmstask.appspot.com',
    measurementId: 'G-LQGT967DXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSE1CMpLX3P7mWpyngud1hWpCZ3KyHl1w',
    appId: '1:1044697442933:android:e6c376a9c29e02d045663c',
    messagingSenderId: '1044697442933',
    projectId: 'cmstask',
    databaseURL: 'https://cmstask-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cmstask.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFk8KrbE1VPveKRwZNehPKEGx-wMOYXtA',
    appId: '1:1044697442933:ios:1ced00640482a81945663c',
    messagingSenderId: '1044697442933',
    projectId: 'cmstask',
    databaseURL: 'https://cmstask-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cmstask.appspot.com',
    iosBundleId: 'com.example.cmsTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFk8KrbE1VPveKRwZNehPKEGx-wMOYXtA',
    appId: '1:1044697442933:ios:1ced00640482a81945663c',
    messagingSenderId: '1044697442933',
    projectId: 'cmstask',
    databaseURL: 'https://cmstask-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cmstask.appspot.com',
    iosBundleId: 'com.example.cmsTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3HzK3qq23AYJoSQIurD2n6ExmLthRmqs',
    appId: '1:1044697442933:web:03184ff6183045a545663c',
    messagingSenderId: '1044697442933',
    projectId: 'cmstask',
    authDomain: 'cmstask.firebaseapp.com',
    databaseURL: 'https://cmstask-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cmstask.appspot.com',
    measurementId: 'G-07R5ZCRM0R',
  );
}
